version: '3.8'

name: fitness_app
services:
  db:
    image: postgres:15-alpine
    container_name: userservice_db
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - userservice_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d userservice"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitness_app

volumes:
  userservice_db:
    driver: local

networks:
  fitness_app:
    driver: bridge